apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: openwhisk-lb
  name: openwhisk-pod
spec:
  containers:
  - name: alpine-ow
    image: yobasystems/alpine-docker
    ports:
    - containerPort: 3233
    command: ["/bin/sh"]
    args: ["-c", "docker run -p 3233:3233 -v /var/run/docker.sock:/var/run/docker.sock --name openwhisk openwhisk/standalone:nightly"]
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: "/var/run/docker.sock"
      name: openwhisk-vol
    resources: {}
  volumes:
    - name: openwhisk-vol
      hostPath:
        path: "/var/run/docker.sock"

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     io.kompose.service: openwhisk-lb
#   name: openwhisk-svc
# spec:
#   type: NodePort
#   ports:
#   - name: "3233"
#     targetPort: 3233
#     protocol: TCP
#     port: 3233
#     nodePort: 30233
#   selector:
#     io.kompose.service: openwhisk-lb
