version: '2'
services:
  fluree-n1:
    image: fluree/ledger
    container_name: fluree-db
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    environment: 
        fdb_group_servers: ce02cf4d03333e5f56f90c35fafd6934e26076c74c6a6c0846078a6cf15e50bf@88.235.154.139:31790
        fdb_group_this_server: ce02cf4d03333e5f56f90c35fafd6934e26076c74c6a6c0846078a6cf15e50bf
        fdb-api-port: 31090
        fdb-join: "false"
    ports:
      - "31090:31090"
      - "31790:31790"
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/16
          gateway: 172.16.238.1