version: '2'
services:
  fluree-n1:
    image: fluree/ledger
    container_name: fluree-db
    networks:
      - default
    environment: 
        fdb_group_servers: serverName1@Ip:Port
        fdb_group_this_server: serverName2
        fdb-group-catch-up-rounds: 100
        fdb-api-port: 80901
        fdb-join: "false"
    ports:
      - "8090:8090"
      - "9790:9790"
